# Generated by Django 4.1 on 2022-10-03 01:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=25, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('wholesale_url', models.URLField()),
                ('wholesaler_price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(default='PMAF6031', editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=25, unique=True)),
                ('profit', models.FloatField(default=0.0, editable=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('is_available', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(to='product.category')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.website')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='product/')),
                ('thumbnail', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='product.product')),
            ],
        ),
    ]
