# Generated by Django 4.1 on 2022-09-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='TEPZ8576', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
