# Generated by Django 4.1 on 2022-09-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_sku_alter_productpictures_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='TQRD4665', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
