# Generated by Django 4.1 on 2022-10-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_sku_alter_productvariant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='XUCI7050', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
