# Generated by Django 4.1 on 2022-10-03 01:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('referral', models.BooleanField(default=False)),
                ('referral_source', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=5)),
                ('valid_address', models.BooleanField(default=False)),
                ('tracking', models.CharField(blank=True, max_length=100, null=True)),
                ('shipped', models.BooleanField(default=False)),
                ('refund', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('full_address', models.TextField(blank=True, editable=False, null=True)),
                ('placed', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('order_number', models.CharField(default='VWAGD48232', editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.website')),
            ],
        ),
    ]
