# Generated by Django 4.1 on 2022-09-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='MEKPN68098', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
