# Generated by Django 4.1 on 2022-10-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='NXTCU60310', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
