# Generated by Django 4.1 on 2022-10-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default='2312833512', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
