# Generated by Django 4.1 on 2022-09-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='favicon',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='website',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
