# Generated by Django 4.1 on 2022-09-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_website_favicon_alter_website_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='favicon',
            field=models.ImageField(upload_to='site/favicon/'),
        ),
        migrations.AlterField(
            model_name='website',
            name='logo',
            field=models.ImageField(upload_to='site/logo/'),
        ),
    ]
